#!/usr/bin/env bash
set -euo pipefail

# Build frontend bundle into react-app/dist and package as tar.gz
# It now also writes a runtime env file (dist/env.js) so deployments can
# override API base without rebuilding images.
# Usage:
#   bash react-app/build.sh                      # build using current env
#   VITE_API_URL=/api bash react-app/build.sh    # set API base to same-origin
#   API_URL=https://api.example.com bash react-app/build.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "[frontend] Installing dependencies (npm ci)"
npm ci

echo "[frontend] Building (npm run build)"
# Vite picks up VITE_* env vars from shell
npm run build

# Inject runtime config (env.js) consumed by index.html
RUNTIME_API_URL="${VITE_API_URL:-${API_URL:-}}"
ENV_JS="dist/env.js"
cat > "$ENV_JS" <<EOF
// Runtime-injected config (generated by build.sh)
window.__APP_CONFIG__ = {
  API_URL: "${RUNTIME_API_URL}"
};
EOF
echo "[frontend] Wrote runtime env: $ENV_JS (API_URL='${RUNTIME_API_URL}')"

OUT=dist
PKG="dist-$(date +%Y%m%d_%H%M%S).tar.gz"
echo "[frontend] Packaging $OUT -> $PKG"
tar -czf "$PKG" -C "$OUT" .

echo "[ok] Bundle: $SCRIPT_DIR/$OUT"
echo "[ok] Package: $SCRIPT_DIR/$PKG"
